name: Deploy

on: [push]

jobs:
  build:
    if: github.ref == 'refs/heads/express-server'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.EXPRESS_SERVER_VPS_HOST }}
        PORT: ${{ secrets.EXPRESS_SERVER_VPS_PORT }}
        USERNAME: ${{ secrets.EXPRESS_SERVER_VPS_USERNAME }}
        KEY: ${{ secrets.EXPRESS_SERVER_VPS_SSHKEY }}
      with:
        source: "."
        target: "/opt/express/talespinner"

    - name: Launch server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EXPRESS_SERVER_VPS_HOST }}
        PORT: ${{ secrets.EXPRESS_SERVER_VPS_PORT }}
        USERNAME: ${{ secrets.EXPRESS_SERVER_VPS_USERNAME }}
        KEY: ${{ secrets.EXPRESS_SERVER_VPS_SSHKEY }}
        script: pm2 reload run_server